# Generated by Django 3.2.6 on 2021-08-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PmCustmr',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=20)),
                ('h_no', models.IntegerField()),
                ('apt_no', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('mart_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pm_custmr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmInsrnce',
            fields=[
                ('ins_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ins_type', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('prem_amt', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'pm_insrnce',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmInvoice',
            fields=[
                ('inv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inv_date', models.DateField()),
                ('due_date', models.DateField()),
                ('i_amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ins_no', models.ForeignKey(db_column='ins_no', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pminsrnce')),
            ],
            options={
                'db_table': 'pm_invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmVehcle',
            fields=[
                ('vin', models.IntegerField(primary_key=True, serialize=False)),
                ('vmake', models.CharField(max_length=20)),
                ('vmodel', models.CharField(max_length=10)),
                ('model_yr', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pm_vehcle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmInAuto',
            fields=[
                ('ins_no', models.OneToOneField(db_column='ins_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.pminsrnce')),
            ],
            options={
                'db_table': 'pm_in_auto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmInHome',
            fields=[
                ('ins_no', models.OneToOneField(db_column='ins_no', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.pminsrnce')),
            ],
            options={
                'db_table': 'pm_in_home',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmPaymnt',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('method', models.CharField(max_length=2)),
                ('p_amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pminvoice')),
            ],
            options={
                'db_table': 'pm_paymnt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmDriver',
            fields=[
                ('licence', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('d_fname', models.CharField(max_length=20)),
                ('d_lname', models.CharField(max_length=20)),
                ('d_mname', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pmvehcle')),
            ],
            options={
                'db_table': 'pm_driver',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pmvehcle',
            name='ins_no',
            field=models.ForeignKey(db_column='ins_no', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pminauto'),
        ),
        migrations.CreateModel(
            name='PmHome',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pur_date', models.DateField()),
                ('pur_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('area', models.DecimalField(decimal_places=3, max_digits=7)),
                ('htype', models.CharField(max_length=1)),
                ('auto_fire_n', models.CharField(max_length=1)),
                ('home_security', models.CharField(max_length=1)),
                ('basement', models.CharField(max_length=1)),
                ('swim_pool', models.CharField(blank=True, max_length=1, null=True)),
                ('ins_no', models.ForeignKey(db_column='ins_no', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pminhome')),
            ],
            options={
                'db_table': 'pm_home',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PmCustInsr',
            fields=[
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cid', models.OneToOneField(db_column='cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.pmcustmr')),
                ('ins_no', models.ForeignKey(db_column='ins_no', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pminsrnce')),
            ],
            options={
                'db_table': 'pm_cust_insr',
                'managed': True,
                'unique_together': {('cid', 'ins_no')},
            },
        ),
    ]
