# Generated by Django 3.2.6 on 2021-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_insertcustrec'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('premium', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
    ]
